### PR TITLE
Add configurable host & port to support usage within Docker containers

### PR DESCRIPTION
**Pull request by jaimeagudo**

### CODE REVIEW

**Comment by sclasen** [comment]
Nice job. Thanks!

**Comment by sclasen** [comment]
@jaimeagudo just published a snapshot to oss.sonatype.  However the cross build blew up on the 2.10 side so only the 2.11 artifacts are there.

Hopefully 1.3.2 is properly cross built at this point and I can remove the workaround in build.sbt, giving it a shop

**Comment by sclasen** [comment]
Yep, that did it, both versions are in oss.sonatype

**Comment by jaimeagudo** [comment]
Thanks for accepting @sclasen, you didn't publish to maven central though, did you? I'd be handy as I don't want to publish your work under my name :)

**Comment by sclasen** [comment]
Can you try out the snapshot?

If you tell me it works correctly, I will cut a non snapshot release

**Comment by jaimeagudo** [comment]
I'd be happy to do it but I am afraid my scenario it's a bit particular so I am not sure how relevant my test would be

**Comment by iangelov** [comment]
Just so you know - I've tested this (rev. cda728120483ee738ece2844d1fa8b0442a5797d) with a containerized akka application - worked like a charm.

**Pull request merged**
